# Generated by Django 4.2.1 on 2023-06-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Загрузка файла',
                'verbose_name_plural': 'Загрузка файла',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(verbose_name='Дата создания')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('park', models.CharField(max_length=255, verbose_name='Парк')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('action_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('tilda_external_product_id', models.CharField(max_length=255, verbose_name='Внешний код товара (Тильда)')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Код')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('date_of_use', models.DateField(blank=True, default=None, null=True, verbose_name='Дата использования')),
                ('ticket_limit', models.CharField(blank=True, default='часовой', max_length=255, null=True, verbose_name='Лимит')),
                ('ticket_day_type', models.CharField(blank=True, default='будние', max_length=255, null=True, verbose_name='Тип дня недели')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
