# Generated by Django 4.2.1 on 2023-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Загрузка файлов',
                'verbose_name_plural': 'Загрузка файлов',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(verbose_name='Дата создания')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('park', models.CharField(max_length=255, verbose_name='Парк')),
                ('creator', models.CharField(max_length=255, verbose_name='Создатель')),
                ('action_name', models.CharField(max_length=255, verbose_name='Название акции')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('date_of_use', models.DateField(blank=True, null=True, verbose_name='Дата использования')),
            ],
        ),
    ]
