# Generated by Django 4.2.1 on 2023-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customadminpage',
            options={'verbose_name': 'Загрузка файла', 'verbose_name_plural': 'Загрузка файла'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='date_of_use',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата использования'),
        ),
    ]
