# Generated by Django 4.2.1 on 2023-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_promocode_notification', models.CharField(default=False, help_text='В выключенном состоянии уведомления отправляются только если email адрес указанный при оформлении из списка раздела Получатели Уведомлений', max_length=255, verbose_name='Email уведомление покупателю после оплаты заказа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
