# Generated by Django 4.2.1 on 2023-05-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_alter_customadminpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип дней недели')),
            ],
            options={
                'verbose_name': 'Тип дней недели',
                'verbose_name_plural': 'Типы дней недели',
            },
        ),
        migrations.CreateModel(
            name='TicketLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Лимит',
                'verbose_name_plural': 'Лимиты',
            },
        ),
        migrations.CreateModel(
            name='TicketPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Парк')),
            ],
            options={
                'verbose_name': 'Парк',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True, verbose_name='Тип билета')),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'Типы билета',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Произвольное наименование')),
                ('tilda_external_product_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний код товара (Тильда)')),
                ('day_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_day_type', to='promocode.ticketdaytype', verbose_name='Тип дней недели')),
                ('limit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_limit', to='promocode.ticketlimit', verbose_name='Лимит')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_park', to='promocode.ticketpark', verbose_name='Парк')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_type', to='promocode.tickettype', verbose_name='Тип билета')),
            ],
        ),
    ]
