# Generated by Django 4.2.1 on 2023-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_active_promocode_notification',
            field=models.BooleanField(default=False, help_text='В выключенном состоянии уведомления отправляются только если email адрес указанный при оформлении из списка раздела Получатели Уведомлений', verbose_name='Email уведомление покупателю после оплаты заказа'),
        ),
    ]
