# Generated by Django 4.2.1 on 2023-06-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код уведомления')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование уведомления')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('content', models.TextField(max_length=2000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Шаблон email уведомления',
                'verbose_name_plural': 'Шаблоны email уведомления',
            },
        ),
        migrations.AlterField(
            model_name='promocode',
            name='ticket_day_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='ticket_limit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лимит билета'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='tilda_external_product_id',
            field=models.CharField(max_length=255, verbose_name='Внешний код'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_active_promocode_notification',
            field=models.BooleanField(default=False, help_text='В выключенном состоянии уведомления отправляются только если email адрес указанный при оформлении есть в списке раздела Получатели Уведомлений', verbose_name='Email уведомление покупателю после оплаты заказа'),
        ),
    ]
