# Generated by Django 4.2.1 on 2023-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0005_alter_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='tilda_external_product_id',
            field=models.CharField(default='rRBPn3h695v10G3aG2aL', max_length=255, verbose_name='Внешний код товара (Тильда)'),
        ),
    ]
