# Generated by Django 4.2.1 on 2023-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0006_promocode_tilda_external_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='ticket_day_type',
            field=models.CharField(blank=True, default='будням', max_length=255, null=True, verbose_name='Тип дня недели'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='ticket_limit',
            field=models.CharField(blank=True, default='часовой', max_length=255, null=True, verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='tilda_external_product_id',
            field=models.CharField(max_length=255, verbose_name='Внешний код товара (Тильда)'),
        ),
    ]
