# Generated by Django 4.2.1 on 2023-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0007_promocode_ticket_day_type_promocode_ticket_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='ticket_day_type',
            field=models.CharField(blank=True, default='будни', max_length=255, null=True, verbose_name='Тип дня недели'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketDayType',
        ),
        migrations.DeleteModel(
            name='TicketLimit',
        ),
        migrations.DeleteModel(
            name='TicketPark',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
