# Generated by Django 4.2.1 on 2023-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0008_alter_promocode_ticket_day_type_delete_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
            },
        ),
    ]
