# Generated by Django 4.2.1 on 2023-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0009_notificationrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='ticket_day_type',
            field=models.CharField(blank=True, default='будние', max_length=255, null=True, verbose_name='Тип дня недели'),
        ),
    ]
